### ISSUE TITLE
Separate downloading and reading of pbf

### ISSUE THREAD

**Issue by mem48** [ITSLeeds/osmextractr#33] opened 2020-01-21 11:41 UTC
The get_geofabric function calls read_pbf at the end. So there is no easy way to download pbf without also loading them into memory. This is bad for thinks like batch downloading.

Instaid the function should just download and return the path to the file.
e.g. 

```
pbf <- get_geofabric("isle of man")
lines <- read_pbf(pbf)
```

**Comment by Robinlovelace** [comment] 2020-01-21 11:44
Or:

```r
gf_download("isle of man")`
lines = get_geofabric("ilsle of wight")
#> data already downloaded, reading from ~/data/osm/...
```

**Comment by mem48** [comment] 2020-01-22 16:49
So you asked for one place and loaded another? Doesn't seem right?

**Comment by Robinlovelace** [comment] 2020-01-22 16:52
No that was just a hypothetical example and a bit of a typo / 'brain fart' by me. Should have said:

```r
gf_download("isle of wight")`
lines = get_geofabric("ilsle of wight")
#> data already downloaded, reading from ~/data/osm/...
```

**Comment by agila5** [comment] 2020-07-11 08:55
This is partially fixed now: 

``` r
# packages
library(osmextractr)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
#> Geofabrik data are taken from https://download.geofabrik.de/
#> For usage details of bbbike data see https://download.bbbike.org/osm/

# read-in
oe_get("Isle of Wight")
#> Reading layer `lines' from data source `/home/andrea/osmext_data/geofabrik_isle-of-wight-latest.gpkg' using driver `GPKG'
#> Simple feature collection with 44365 features and 9 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: -5.401978 ymin: 43.35489 xmax: -0.175775 ymax: 50.89599
#> geographic CRS: WGS 84

# just the path
oe_get("Isle of Wight", download_only = TRUE)
#> [1] "/home/andrea/osmext_data/geofabrik_isle-of-wight-latest.gpkg"
```

<sup>Created on 2020-07-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment] 2020-07-12 13:41
I say that this means the issue is fixed, just noticed the `download_only` option. Work for you @mem48 ?

**Comment by mem48** [comment] 2020-07-12 14:23
Seems like a good solution to me

**Comment by Robinlovelace** [comment] 2020-07-12 14:28
OK, thanks @mem48 closing for now. Please test drive the updated package and open any issues you find.

**Closed by Robinlovelace** 2020-07-12 14:28 UTC
