### ISSUE TITLE
Bug when trying to download data from Central America

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/osmextractr#25] opened 2019-11-15 14:01 UTC
Any ideas @agila5 ?

``` r
library(geofabric)
place_sf = sf::st_as_sf(data.frame(x = -86, y = 15, n = 1),
                        coords = c("x", "y"), crs = 4326)
osm_data_place = get_geofabric(place_sf)
#> although coordinates are longitude/latitude, st_contains assumes that they are planar
#> The place is within these geofabrik zones: Central America
#> Selecting the smallest:
#> Error in if (interactive() & ask & large_size) {: argument is of length zero
plot(osm_data_place["highway"])
#> Error in plot(osm_data_place["highway"]): object 'osm_data_place' not found
```

<sup>Created on 2019-11-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by agila5** [comment] 2019-11-15 14:23
The problem is here 
https://github.com/ITSLeeds/geofabric/blob/170dda88c73d716d0d8fe38b09f6c3721d1d65b9/R/gf_find.R#L49
since in some cases geofabric_all_matches$level can be NA. Not sure why since the geofabric_zones.R file is quite messy and I don't fully understand that. 

I can try polish that first and then work on this issue.

**Comment by Robinlovelace** [comment] 2019-11-15 14:24
Good point. Overall we need to re-build the `geofabric_regions` data file to solve this at a higher level. Also, do you know a way to convert `MB` and `GB` file sizes into a single numeric unit (MB I suggest)?

**Comment by agila5** [comment] 2019-11-15 14:41
> Also, do you know a way to convert MB and GB file sizes into a single numeric unit (MB I suggest)?

Nope. It shouldn't be too difficult to write an adhoc function to translate something like `(3.4 GB)` into a numeric MB. I'll try 😅

**Comment by agila5** [comment] 2019-11-19 12:44
> Also, do you know a way to convert MB and GB file sizes into a single numeric unit (MB I suggest)?

I was thinking of something like this: 

``` r
# packages
library(tidyverse)

# example
size_pbf <- c("(3.4 GB)", "(29.0 MB)", "(7.4 GB)", "(709 MB)", "(365 MB)", "(20.5 GB)", "(8.7 GB)", "(1.7 GB)")

my_fix_size_pbf <- function(size_pbf) {
  GB_flag <- str_detect(size_pbf, "GB")
  size_as_test <- str_extract(size_pbf, "(?:(?=\\d+\\.)\\d+\\.\\d+|\\d+)")
  # the idea is: if the string contains a sequence of digits and a full stop,
  # like 3.4, then extract the sequence of digits, the full stop, and all the
  # digits after the full stop; otherwise extract only the sequence of digits
  # (like 709)
  size_as_numeric <- as.numeric(size_as_test)
  # multiply GB data per 1000 (or 1024, I don't know)
  result <- if_else(GB_flag, size_as_numeric * 1000, size_as_numeric)
  result
}
my_fix_size_pbf(size_pbf)
#> [1]  3400    29  7400   709   365 20500  8700  1700
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Do you know any simpler approach? And do you prefer to multiply GB to MB times 1000 or 1024 (It doesn't matter that much I think)?

**Comment by Robinlovelace** [comment] 2019-11-19 12:55
That looks good to me, many thanks Andrea! Next step: update the package data accordingly. Happy to rebuild the `geofabric_zones` with updated size estimates based on your rather nice function - won't be until next week though so if you fancy giving it a bash, go for it (althought there may be other priorities like `rnet-rj` ; ).

**Comment by Robinlovelace** [comment] 2019-11-19 12:55
I think multiplying by 1024 may be correct but not 100% sure...

**Comment by agila5** [comment] 2019-11-19 13:09
I'm already working a new version of geofabric_zones in the "free" time and I think I will create a PR as soon as possible

**Comment by agila5** [comment] 2020-07-10 09:16
Fixed with the new approach

**Closed by agila5** 2020-07-10 09:16 UTC
